version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    build: ./nifi
    container_name: nifi
    ports:
      - 8080
    volumes:
      - ./src/:/src/
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
  # ======= HDFS =======
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020
  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
    depends_on:
      - namenode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
  hue:
    image: bde2020/hdfs-filebrowser:3.11
    container_name: hue
    ports:
      - 8088:8088
    environment:
      - NAMENODE_HOST=namenode
   # ======= ELASTICSEARCH =======
  elasticsearch1: # Elasticsearch Instance
    container_name: elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - node.name=elasticsearch1
      - discovery.seed_hosts=elasticsearch2
      - bootstrap.memory_lock=true      
      - cluster.name=article-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      esnet:
        aliases:
          - elasticsearch
  elasticsearch2:
    container_name: elasticsearch2
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - node.name=elasticsearch2
      - discovery.seed_hosts=elasticsearch1
      - cluster.name=article-cluster
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - bootstrap.memory_lock=true            
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      esnet:
        aliases:
          - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    container_name: kibana
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601    
    depends_on: 
      - elasticsearch1
      - elasticsearch2
    networks:
      esnet:


volumes:
  esdata1:  
    driver: local
  esdata2:
    driver: local

networks: 
  esnet:
    driver: bridge